<a href="https://colab.research.google.com/github/andrii0yerko/IASA-Intelligent-Data-Analysis/blob/main/Yerko_CP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<center><font size="6"><b>Комп'ютерний практикум 2.

Python для математичних обчислень</b></font></center>

##<center>__Самостійні завдання__</center>

> Скопіювати блок самостійних завдань в окремий файл ***LastName_CP2.ipynb***

> Інсталюйте необхідні пакети бібліотек Python

### Завдання №1

1. Задати матрицю $A$ розмірності $4х5$ з цілих чисел. 
2. Вивести другий рядок матриці $A$.
3. Вивести третій стовпчик матриці $A$. 
4. Вивести елемент $a_{13}$
5. Транспонувати матрицю $A$
5. Вивести матрицю $B$, яка є частиною матриці $A$ з перших трьох рядків та стовпців.
6. Знайти визначник матриці $B$

In [1]:
# МІСЦЕ ДЛЯ КОДУ
import numpy as np

A = np.arange(4 * 5).reshape(4, 5)

print(A[1])
print(A[:, 2])
print(A[0, 2])
print(A.T)

B = A[:3, :3]
print(B)

print(np.linalg.det(B))

[5 6 7 8 9]
[ 2  7 12 17]
2
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
0.0


### Завдання №2

1. Задати матрицю $A$ розмірності $2х3$ з цілих чисел. 
2. Задати матрицю $B$ розмірності $3х2$ з цілих чисел
3. Обчислити добуток $AB$ та $BA$ 
4. Перемножити поелементно $AB^T$ $BA^T$
5. Обчислити вираз $(2A-3B^T)N$, де $N$ - квадратна матриця з одиниць, порядку, що дозволяє оперцію множення


In [2]:
# МІСЦЕ ДЛЯ КОДУ

A = np.arange(2 * 3).reshape(2, 3)
B = np.arange(2 * 3).reshape(3, 2)

print(A @ B)
print(B @ A)

print(A * B.T)
print(B * A.T)

tmp = (2 * A - 3 * B.T)
N = np.ones((tmp.shape[1], tmp.shape[1]))
tmp @ N

[[10 13]
 [28 40]]
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
[[ 0  2  8]
 [ 3 12 25]]
[[ 0  3]
 [ 2 12]
 [ 8 25]]


array([[-12., -12., -12.],
       [ -3.,  -3.,  -3.]])

### Завдання №3

Знайти розв'язок системи лінійних рівнянь
$$\begin{cases}
   2x_1+5x_2-4x_3=-3\\
   3x_1-8x_2+3x_3=11\\
   5x_1+6x_2-4x_3=-1
 \end{cases} $$. 
1. Перевірити за теоремою Кронекера-Капеллі, що система має єдиний розв'язок
1. За допомогою вбудованої функції з бібліотеки Python
2. За допомогою матричного методу
3. За допомогою методу Крамера 
4. Зробити перевірку, що знайдений розв'язок задовільняє систему
5. Знайти власні числа та власні вектори матриці А


In [3]:
# МІСЦЕ ДЛЯ КОДУ

A = np.array(
    [
        [2, 5, -4],
        [3, -8, 3],
        [5, 6, -4]
    ]
)

b = np.array([-3, 11, -1])

# 1
assert np.linalg.matrix_rank(A) == np.linalg.matrix_rank(np.column_stack([A, b]))

# 2
inbuilt = np.linalg.solve(A, b)

# 3
matrix_method = np.linalg.inv(A) @ b

# 4
def with_column(matrix, index, replacement):
    matrix = matrix.copy()
    matrix[:, index] = replacement
    return matrix

cramers_method = [np.linalg.det(with_column(A, i, b)) for i in range(A.shape[-1])]
cramers_method = np.divide(cramers_method, np.linalg.det(A))

# 5
assert np.isclose(inbuilt, matrix_method).all()
assert np.isclose(inbuilt, cramers_method).all()

assert np.isclose(A @ inbuilt, b).all()

# 6
eigvals, eigvects = np.linalg.eig(A)
eigvals, eigvects

(array([  0.51083043+2.44937783j,   0.51083043-2.44937783j,
        -11.02166086+0.j        ]),
 array([[-0.26574728-0.36956459j, -0.26574728+0.36956459j,
          0.43184973+0.j        ],
        [-0.38275228-0.02011423j, -0.38275228+0.02011423j,
         -0.81414291+0.j        ],
        [-0.80367687+0.j        , -0.80367687-0.j        ,
          0.38817153+0.j        ]]))

In [4]:
cramers_method

array([ 1.00000000e+00, -1.00000000e+00,  7.46584759e-16])

### Завдання №4

Знайти границі функції:

1. $$\lim_{x\to\infty} \frac{2x^3+3x^2-7}{4x^2+5x-8}$$

2. $$\lim_{x\to\infty} \left(\frac{x+4}{x+8}\right)^{-3x}$$
3. $$\lim_{x\to 0} \frac{x^2+x-12}{\sqrt{x-2}-\sqrt{4-x}}$$
4. $$\lim_{x\to 2} \frac{x^2-5x+6}{x^2-12x+20}$$
5. $$\lim_{x\to 0} \frac{\tan(3x)-\sin(3x)}{2x^2}$$






In [5]:
 #МІСЦЕ ДЛЯ КОДУ

from IPython.display import display
from sympy import *

x = Symbol("x")

display(limit((2 * x ** 3 + 3 * x ** 2 - 7) / (4 * x**2 + 5 * x - 8), x, oo))

display(limit(((x + 4) / (x + 8)) ** (-3 * x), x, oo))

lim = limit((x ** 2 + x - 12) / (sqrt(x - 2) - sqrt(4 - x)), x, 0)
display(lim)

lim = limit((x ** 2 - 5 * x + 6) / (x ** 2 - 12 * x + 20), x, 2)
display(lim)

lim = limit((tan(3 * x) - sin(3 * x)) / (2 * x ** 2), x, 2)
display(lim)

oo

exp(12)

-12/(-2 + sqrt(2)*I)

1/8

tan(6)/8 - sin(6)/8

### Завдання №5

Знайти похідну функцій

1. $$y=x\sin^3(3x)$$
1. $$y=\ln(x^4-\cos^2(x))$$
2. $$y=x^2\tan(2x)+e^{6x}$$
3. Знайти похідні до 3-го порядку включно
$$y=x^2-5\sin(4x)+3^{2x} $$



In [6]:
# МІСЦЕ ДЛЯ КОДУ

display(diff(x * sin(3 * x) ** 3, x))
display(diff(ln(x** 4 - cos(x) ** 2), x))
display(diff(x ** 2 * tan(2 * x) + E ** (6 * x), x))


func = x ** 2 - 5 * sin(4 * x) + 3 ** (2 * x)
display(diff(func, x, 1))
display(diff(func, x, 2))
display(diff(func, x, 3))

9*x*sin(3*x)**2*cos(3*x) + sin(3*x)**3

(4*x**3 + 2*sin(x)*cos(x))/(x**4 - cos(x)**2)

x**2*(2*tan(2*x)**2 + 2) + 2*x*tan(2*x) + 6*exp(6*x)

2*3**(2*x)*log(3) + 2*x - 20*cos(4*x)

2*(2*3**(2*x)*log(3)**2 + 40*sin(4*x) + 1)

8*(3**(2*x)*log(3)**3 + 40*cos(4*x))

### Завдання №6

Знайти невизначений інеграл

1. $$\int \frac{2-x}{4x^2+16x-12} \,dx$$
1. $$\int \frac{7x-1}{\sqrt{2x^2-x+5}} \,dx$$
3. $$\int \frac{\ln(x)}{x^3} \,dx$$
4. $$\int \frac{x\arccos(2x)}{\sqrt{1-4x^2}} \,dx$$

Обчислити визначений інтеграл

1. $$\int_{1}^{2} 3(x-1)^2 \,dx$$
2. $$\int_{0}^{\pi/2} \sin^3(x) \,dx$$
3. $$\int_{1}^{+\infty} \frac{1}{x^2+4x+13} \,dx$$
4. $$\int_{1}^{+\infty} \frac{2+\sin(x)}{\sqrt{x}},dx$$


In [7]:
# МІСЦЕ ДЛЯ КОДУ

display(integrate((2 - x) / (4 * x ** 2 + 16 * x - 12), x))
display(integrate((7 * x - 1) / sqrt(2 * x ** 2 - x + 5), x))
display(integrate(ln(x) / x ** 3, x))
display(integrate((x * acos(2 * x)) / sqrt(1 - 4 * x ** 2), x))

display(integrate(3 * (x - 1) ** 2, (x, 1, 2)))
display(integrate(sin(x) ** 3, (x, 0, pi / 2)))
display(integrate(1 / (x ** 2 + 4 * x + 13), (x, 1, oo)))
# display(integrate((2 + sin(x)) / sqrt(x), (x, 1, oo)))  # does not converge

-(1/8 + sqrt(7)/14)*log(x + 2 + sqrt(7)) - (1/8 - sqrt(7)/14)*log(x - sqrt(7) + 2)

Integral((7*x - 1)/sqrt(2*x**2 - x + 5), x)

-log(x)/(2*x**2) - 1/(4*x**2)

-x/2 - sqrt(1 - 4*x**2)*acos(2*x)/4

1

2/3

pi/12